"""Data source definitions for Project GIGDIS beta1.1."""

RSS_SOURCES = [
    {
        "name": "Reuters World News",
        "url": "https://feeds.reuters.com/reuters/worldNews",
        "credibility": 0.95,
    },
    {
        "name": "BBC World",
        "url": "http://feeds.bbci.co.uk/news/world/rss.xml",
        "credibility": 0.92,
    },
    {
        "name": "Al Jazeera",
        "url": "https://www.aljazeera.com/xml/rss/all.xml",
        "credibility": 0.88,
    },
    {
        "name": "Reuters Technology",
        "url": "https://feeds.reuters.com/reuters/technologyNews",
        "credibility": 0.93,
    },
    {
        "name": "Reuters Business",
        "url": "https://feeds.reuters.com/reuters/businessNews",
        "credibility": 0.93,
    },
    {
        "name": "BBC Technology",
        "url": "http://feeds.bbci.co.uk/news/technology/rss.xml",
        "credibility": 0.9,
    },
    {
        "name": "UN News",
        "url": "https://news.un.org/feed/subscribe/en/news/all/rss.xml",
        "credibility": 0.9,
    },
    {
        "name": "NPR World",
        "url": "https://feeds.npr.org/1004/rss.xml",
        "credibility": 0.89,
    },
    {
        "name": "CNN World",
        "url": "http://rss.cnn.com/rss/edition_world.rss",
        "credibility": 0.87,
    },
]

COUNTRY_KEYWORDS = {
    "Ukraine": ["ukraine", "kyiv", "kiev", "dnipro"],
    "Russia": ["russia", "moscow", "kremlin"],
    "Israel": ["israel", "tel aviv", "jerusalem", "gaza"],
    "Palestine": ["palestine", "west bank", "ramallah"],
    "United States": ["united states", "u.s.", "washington", "new york"],
    "China": ["china", "beijing", "shanghai", "taiwan"],
    "Japan": ["japan", "tokyo"],
    "United Kingdom": ["united kingdom", "uk", "london", "britain"],
    "France": ["france", "paris"],
    "Germany": ["germany", "berlin"],
    "India": ["india", "new delhi", "mumbai"],
    "Pakistan": ["pakistan", "islamabad"],
    "Iran": ["iran", "tehran"],
    "Turkey": ["turkey", "ankara", "istanbul"],
    "South Korea": ["south korea", "seoul"],
    "North Korea": ["north korea", "pyongyang"],
    "Canada": ["canada", "ottawa", "toronto"],
    "Mexico": ["mexico", "mexico city"],
    "Brazil": ["brazil", "brasilia", "rio"],
    "Australia": ["australia", "canberra", "sydney"],
    "Indonesia": ["indonesia", "jakarta"],
    "Saudi Arabia": ["saudi arabia", "riyadh"],
    "Egypt": ["egypt", "cairo"],
    "South Africa": ["south africa", "johannesburg", "pretoria"],
    "Italy": ["italy", "rome"],
    "Spain": ["spain", "madrid"],
}

COUNTRY_COORDS = {
    "Ukraine": (48.3794, 31.1656),
    "Russia": (61.5240, 105.3188),
    "Israel": (31.0461, 34.8516),
    "Palestine": (31.9522, 35.2332),
    "United States": (39.8283, -98.5795),
    "China": (35.8617, 104.1954),
    "Japan": (36.2048, 138.2529),
    "United Kingdom": (55.3781, -3.4360),
    "France": (46.2276, 2.2137),
    "Germany": (51.1657, 10.4515),
    "India": (20.5937, 78.9629),
    "Pakistan": (30.3753, 69.3451),
    "Iran": (32.4279, 53.6880),
    "Turkey": (38.9637, 35.2433),
    "South Korea": (35.9078, 127.7669),
    "North Korea": (40.3399, 127.5101),
    "Canada": (56.1304, -106.3468),
    "Mexico": (23.6345, -102.5528),
    "Brazil": (-14.2350, -51.9253),
    "Australia": (-25.2744, 133.7751),
    "Indonesia": (-0.7893, 113.9213),
    "Saudi Arabia": (23.8859, 45.0792),
    "Egypt": (26.8206, 30.8025),
    "South Africa": (-30.5595, 22.9375),
    "Italy": (41.8719, 12.5674),
    "Spain": (40.4637, -3.7492),
}

TOPIC_KEYWORDS = {
    "military": ["war", "airstrike", "missile", "military", "armed forces", "troop", "defense ministry", "artillery", "frontline", "ceasefire", "drone strike"],
    "politics": ["election", "parliament", "government", "president", "prime minister", "policy"],
    "technology": ["ai", "chip", "semiconductor", "software", "cyber", "tech", "startup"],
    "science": ["space", "nasa", "research", "scientist", "laboratory", "climate"],
    "disaster": ["earthquake", "flood", "hurricane", "wildfire", "disaster"],
    "public-health": ["virus", "disease", "outbreak", "health emergency", "who", "vaccination"],
    "diplomacy": ["summit", "talks", "diplomatic", "sanction", "treaty", "ceasefire", "negotiation"],
    "economy": ["inflation", "oil", "market", "trade", "economic", "tariff", "gdp", "interest rate", "recession"],
}

AVAILABLE_TOPICS = [
    "military",
    "politics",
    "technology",
    "science",
    "disaster",
    "public-health",
    "diplomacy",
    "economy",
    "general",
]
