"""Data source definitions for Project GIGDIS beta3.3."""

SOURCE_TYPES = {
    "mainstream": {"zh": "主流媒体", "en": "Mainstream"},
    "local": {"zh": "地方媒体", "en": "Local"},
    "non_neutral": {"zh": "非中立媒体", "en": "Non-neutral"},
}

RSS_SOURCES = [
    {"name": "Reuters World News", "url": "https://feeds.reuters.com/reuters/worldNews", "credibility": 0.95, "type": "mainstream"},
    {"name": "BBC World", "url": "http://feeds.bbci.co.uk/news/world/rss.xml", "credibility": 0.92, "type": "mainstream"},
    {"name": "Reuters Technology", "url": "https://feeds.reuters.com/reuters/technologyNews", "credibility": 0.93, "type": "mainstream"},
    {"name": "Reuters Business", "url": "https://feeds.reuters.com/reuters/businessNews", "credibility": 0.93, "type": "mainstream"},
    {"name": "BBC Technology", "url": "http://feeds.bbci.co.uk/news/technology/rss.xml", "credibility": 0.90, "type": "mainstream"},
    {"name": "UN News", "url": "https://news.un.org/feed/subscribe/en/news/all/rss.xml", "credibility": 0.90, "type": "mainstream"},
    {"name": "NPR World", "url": "https://feeds.npr.org/1004/rss.xml", "credibility": 0.89, "type": "mainstream"},
    {"name": "CNN World", "url": "http://rss.cnn.com/rss/edition_world.rss", "credibility": 0.87, "type": "mainstream"},
    {"name": "AP Top News", "url": "https://apnews.com/hub/ap-top-news?output=1", "credibility": 0.91, "type": "mainstream"},
    {"name": "The Guardian World", "url": "https://www.theguardian.com/world/rss", "credibility": 0.87, "type": "mainstream"},
    {"name": "NPR Politics", "url": "https://feeds.npr.org/1014/rss.xml", "credibility": 0.88, "type": "mainstream"},
    {"name": "BBC Africa", "url": "http://feeds.bbci.co.uk/news/world/africa/rss.xml", "credibility": 0.91, "type": "mainstream"},
    {"name": "AllAfrica", "url": "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf", "credibility": 0.84, "type": "mainstream"},
    {"name": "Africanews", "url": "https://www.africanews.com/feed/rss", "credibility": 0.82, "type": "mainstream"},
    {"name": "The Local Europe", "url": "https://www.thelocal.com/rss/", "credibility": 0.78, "type": "local"},
    {"name": "The Times of India", "url": "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms", "credibility": 0.76, "type": "local"},
    {"name": "ABC News Australia", "url": "https://www.abc.net.au/news/feed/51120/rss.xml", "credibility": 0.80, "type": "local"},
    {"name": "Nikkei Asia", "url": "https://asia.nikkei.com/rss/feed/nar", "credibility": 0.82, "type": "local"},
    {"name": "News24 South Africa", "url": "https://feeds.news24.com/articles/news24/TopStories/rss", "credibility": 0.79, "type": "local"},
    {"name": "Punch Nigeria", "url": "https://punchng.com/feed/", "credibility": 0.74, "type": "local"},
    {"name": "Daily Maverick South Africa", "url": "https://www.dailymaverick.co.za/feed/", "credibility": 0.77, "type": "local"},
    {"name": "The Namibian", "url": "https://www.namibian.com.na/feed/", "credibility": 0.73, "type": "local"},
    {"name": "Al Jazeera", "url": "https://www.aljazeera.com/xml/rss/all.xml", "credibility": 0.88, "type": "non_neutral"},
    {"name": "Fox News World", "url": "https://moxie.foxnews.com/google-publisher/world.xml", "credibility": 0.72, "type": "non_neutral"},
    {"name": "RT World News", "url": "https://www.rt.com/rss/news/", "credibility": 0.62, "type": "non_neutral"},
    {"name": "Breitbart World", "url": "https://www.breitbart.com/feed/", "credibility": 0.58, "type": "non_neutral"},
    {"name": "Egypt Today", "url": "https://www.egypttoday.com/Home/RSS?CategoryId=1", "credibility": 0.66, "type": "non_neutral"},
    {"name": "Sahara Reporters", "url": "https://saharareporters.com/feeds/latest/feed.xml", "credibility": 0.61, "type": "non_neutral"},
]

COUNTRY_KEYWORDS = {
    "Ukraine": ["ukraine", "kyiv", "kiev", "dnipro"],
    "Russia": ["russia", "moscow", "kremlin"],
    "Israel": ["israel", "tel aviv", "jerusalem", "gaza"],
    "Palestine": ["palestine", "west bank", "ramallah"],
    "United States": ["united states", "u.s.", "washington", "new york"],
    "China": ["china", "beijing", "shanghai", "taiwan"],
    "Japan": ["japan", "tokyo"],
    "United Kingdom": ["united kingdom", "uk", "london", "britain"],
    "France": ["france", "paris"],
    "Germany": ["germany", "berlin"],
    "India": ["india", "new delhi", "mumbai"],
    "Pakistan": ["pakistan", "islamabad"],
    "Iran": ["iran", "tehran"],
    "Turkey": ["turkey", "ankara", "istanbul"],
    "South Korea": ["south korea", "seoul"],
    "North Korea": ["north korea", "pyongyang"],
    "Canada": ["canada", "ottawa", "toronto"],
    "Mexico": ["mexico", "mexico city"],
    "Brazil": ["brazil", "brasilia", "rio"],
    "Australia": ["australia", "canberra", "sydney"],
    "Indonesia": ["indonesia", "jakarta"],
    "Saudi Arabia": ["saudi arabia", "riyadh"],
    "Egypt": ["egypt", "cairo"],
    "South Africa": ["south africa", "johannesburg", "pretoria"],
    "Nigeria": ["nigeria", "abuja", "lagos"],
    "Kenya": ["kenya", "nairobi"],
    "Ethiopia": ["ethiopia", "addis ababa"],
    "Sudan": ["sudan", "khartoum", "darfur"],
    "Morocco": ["morocco", "rabat", "casablanca"],
    "Algeria": ["algeria", "algiers"],
    "Tunisia": ["tunisia", "tunis"],
    "Ghana": ["ghana", "accra"],
    "Tanzania": ["tanzania", "dodoma", "dar es salaam"],
    "Uganda": ["uganda", "kampala"],
    "Democratic Republic of the Congo": ["democratic republic of the congo", "dr congo", "kinshasa", "congo"],
    "Italy": ["italy", "rome"],
    "Spain": ["spain", "madrid"],
}

COUNTRY_COORDS = {
    "Ukraine": (48.3794, 31.1656),
    "Russia": (61.5240, 105.3188),
    "Israel": (31.0461, 34.8516),
    "Palestine": (31.9522, 35.2332),
    "United States": (39.8283, -98.5795),
    "China": (35.8617, 104.1954),
    "Japan": (36.2048, 138.2529),
    "United Kingdom": (55.3781, -3.4360),
    "France": (46.2276, 2.2137),
    "Germany": (51.1657, 10.4515),
    "India": (20.5937, 78.9629),
    "Pakistan": (30.3753, 69.3451),
    "Iran": (32.4279, 53.6880),
    "Turkey": (38.9637, 35.2433),
    "South Korea": (35.9078, 127.7669),
    "North Korea": (40.3399, 127.5101),
    "Canada": (56.1304, -106.3468),
    "Mexico": (23.6345, -102.5528),
    "Brazil": (-14.2350, -51.9253),
    "Australia": (-25.2744, 133.7751),
    "Indonesia": (-0.7893, 113.9213),
    "Saudi Arabia": (23.8859, 45.0792),
    "Egypt": (26.8206, 30.8025),
    "South Africa": (-30.5595, 22.9375),
    "Nigeria": (9.0820, 8.6753),
    "Kenya": (-0.0236, 37.9062),
    "Ethiopia": (9.1450, 40.4897),
    "Sudan": (12.8628, 30.2176),
    "Morocco": (31.7917, -7.0926),
    "Algeria": (28.0339, 1.6596),
    "Tunisia": (33.8869, 9.5375),
    "Ghana": (7.9465, -1.0232),
    "Tanzania": (-6.3690, 34.8888),
    "Uganda": (1.3733, 32.2903),
    "Democratic Republic of the Congo": (-4.0383, 21.7587),
    "Italy": (41.8719, 12.5674),
    "Spain": (40.4637, -3.7492),
}

TOPIC_KEYWORDS = {
    "military": ["war", "airstrike", "missile", "military", "armed forces", "troop", "defense ministry", "artillery", "frontline", "ceasefire", "drone strike"],
    "politics": ["election", "parliament", "government", "president", "prime minister", "policy"],
    "technology": ["ai", "chip", "semiconductor", "software", "cyber", "tech", "startup"],
    "science": ["space", "nasa", "research", "scientist", "laboratory", "climate"],
    "disaster": ["earthquake", "flood", "hurricane", "wildfire", "disaster"],
    "public-health": ["virus", "disease", "outbreak", "health emergency", "who", "vaccination"],
    "diplomacy": ["summit", "talks", "diplomatic", "sanction", "treaty", "ceasefire", "negotiation"],
    "economy": ["inflation", "oil", "market", "trade", "economic", "tariff", "gdp", "interest rate", "recession"],
}

AVAILABLE_TOPICS = [
    "military",
    "politics",
    "technology",
    "science",
    "disaster",
    "public-health",
    "diplomacy",
    "economy",
    "general",
]
